language: go
sudo: false
go:
  - tip

services:
  - mysql
  - redis-server

env:
  global:
    - GO111MODULE=on

before_install:
  - go get github.com/mattn/goveralls
  - go get golang.org/x/tools/cmd/cover
  - go get github.com/golangci/golangci-lint/cmd/golangci-lint

install:
  - go mod download

script:
  #- golangci-lint run
  - go test -v -race -covermode=atomic -coverprofile=profile.cov ./cmd/ginserver/... ./configs/travis.toml -om 0
  - goveralls -coverprofile=profile.cov -service=travis-ci

branches:
  only:
    - master
