#docker-compose.yml
#- mysql:5.7
#- redis:3.2
#- web from Dockerfile of web (build is required)
version: '2'
services:
  # MySQL
  mysql:
    #env_file: .env
    image: mysql:5.7
    container_name: web-mysql
    ports:
      - "23306:3306"
    volumes:
      - ./docker_build/mysql/conf:/etc/mysql/conf.d
      - ./docker_build/mysql/db_data:/var/lib/mysql
      - ./docker_build/mysql/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiromaily
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678
  # Redis
  redis:
    image: redis:3.2
    container_name: web-redis
    ports:
      - "26379:6379"
    volumes:
      - ./docker_build/redis/data:/data
    restart: always
    command: redis-server --requirepass password --appendonly yes
  # Mongo
  mongo:
    image: mongo:3.3
    container_name: web-mongo
    ports:
      - "30017:27017"
  # golang:go-gin-wrapper
  web:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  redisHostName: redis-server
      #  mysqlHostName: mysql-server
    image: go-gin-wrapper:v1.1
    container_name: web
    ports:
      - "9999:9999"
    volumes:
      - ./docker_build/logs:/var/log/goweb
      - ./:/go/src/github.com/hiromaily/go-gin-wrapper
    environment:
      ENC_KEY: ${ENC_KEY}
      ENC_IV: ${ENC_IV}
    links:
      - mysql:mysql-server
      - redis:redis-server
      - mongo:mongo-server
    depends_on:
      - mysql
      - redis
      - mongo
    stdin_open: true
    tty: true
    restart: always
    command: bash
    #command: bash ./docker-entrypoint.sh
