#- mysql:5.7
#- redis:3.2
#- web from Dockerfile of web (build is required)
version: '3.0'

volumes:
  db: {}
  rdb: {}

services:
  # MySQL
  mysql:
    #env_file: .env
    image: mysql:5.7
    container_name: web-mysql
    ports:
      - "3306"
    volumes:
      - db:/var/lib/mysql
      - ./docker/mysql/conf.d:/etc/mysql/conf.d
      - ./docker/mysql/init.d:/docker-entrypoint-initdb.d
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hiromaily
      MYSQL_USER: hiromaily
      MYSQL_PASSWORD: 12345678

  # Redis
  redis:
    image: redis:3.2
    container_name: web-redis
    ports:
      - "6379"
    volumes:
      - rdb:/data
    restart: always
    command: redis-server --requirepass password --appendonly yes

  # Mongo
  mongo:
    build:
      context: ./docker/mongo/
      dockerfile: Dockerfile
      args:
        mongo_port: 27017
    #image: mongo:3.4
    image: go-gin-wrapper-mongo:1.0
    container_name: web-mongo
    ports:
      - "27017"
    #command: bash ./init.sh

  # golang:go-gin-wrapper
  web:
    build:
      context: .
      dockerfile: Dockerfile
      #args:
      #  redisHostName: redis-server
      #  mysqlHostName: mysql-server
    image: go-gin-wrapper:1.0
    container_name: web
    ports:
      - "8080"
    environment:
      ENC_KEY: ${ENC_KEY}
      ENC_IV: ${ENC_IV}
    links:
      - mysql:mysql-server
      - redis:redis-server
      - mongo:mongo-server
    depends_on:
      - mysql
      - redis
      - mongo
    restart: always
    command: /go/bin/ginserver -f ./data/toml/docker.toml
