#local, heroku, docker, staging, production
environment = "docker"

[server]
scheme = "http"
host = "docker.hiromaily.com"
port = 9999
num = 1

[server.docs]
path = "/go/src/github.com/hiromaily/go-gin-wrapper"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "172.18.0.1"     # "proxy-server"
port = 9990

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

[api]
header = "X-Custom-Header-Gin"
key = "key12345"
only_ajax = true

[mysql]
host = "mysql-server"
port = 3306
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

[mysql.test]
host = "mysql-server"
port = 3306
dbname = "hiromaily2"
user = "root"
pass = "root"

[redis]
host = "redis-server"
port = 6379
pass = "password"
session = true

[mongodb]
host = "web-mongo"
port = 27017
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

[aws]
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

[develop]
profile_enable = false
recover_enable = true