#local, heroku, docker, staging, production
environment = "heroku"

[server]
scheme = "http"
host = "ginserver.herokuapp.com"
port = 5000

[server.docs]
path = "/app"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "127.0.0.1"
port = 9990
web_port = [ 9997, 9998, 9999 ]

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

[api]
only_ajax = true

[api.cors]
enabled = true
origins = ["localhost:8000"]
headers = ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"]
methods = ["GET", "OPTIONS"]
credentials = false

[api.header]
enabled = true
header = "X-Custom-Header-Gin"
key = "key12345"

[api.jwt]
mode = 1   #0:off, 1:HMAC, 2:RSA
secret_code = "secret1234567890"
private_key = ""
public_key = ""

[auth]

[auth.google]
encrypted = true
client_id = "HC/Tl3lSXPc//PhSP3XgznaU4mgUk7gZ820SG46V+PbhjfC7I58TngiprkepNm4/+StFfhSredc1g/MNiXBKVBxEQ5BtoxqPIyl5SW8c5lk="
client_secret = "x3S1U1d23Y63euKsg5Ytqjt6n/WLORz7npw/oqyIArE="
call_back_url = "https://ginserver.herokuapp.com/oauth2/google/callback"

[auth.facebook]
encrypted = true
client_id = "25XF6XoUu5tbky0h7z+zUg=="                          #app_id
client_secret = "EBN/1raNRI2Fvzk6rJ+K++c5KkMsstxp6AiHGFlE8nY="  #app secret
call_back_url = "https://ginserver.herokuapp.com/oauth2/facebook/callback"

[mysql]
encrypted = false
host = ""
port = 3306
dbname = ""
user = ""
pass = ""

[mysql.test]
encrypted = false
host = ""
port = 3306
dbname = ""
user = ""
pass = ""

[redis]
encrypted = false
host = ""
port = 0
pass = ""
session = true

[mongodb]
encrypted = false
host = ""
port = 0
dbname = ""
user = ""
pass = ""

[aws]
encrypted = false
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

[develop]
profile_enable = false
recover_enable = false