#local, heroku, docker, staging, production
environment = "local"

[server]
scheme = "http"
host = "localhost"
port = 9999
num = 1

[server.docs]
path = "/Users/hy/work/go/src/github.com/hiromaily/go-gin-wrapper"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "127.0.0.1"
port = 9990

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

[auth]

[auth.api]
header = "X-Custom-Header-Gin"
key = "key12345"
only_ajax = true

[auth.jwt]
mode = 2   #0:off, 1:HMAC, 2:RSA
secret_code = ""
private_key = "/Users/hy/.ssh/jwt_rsa"
public_key = "/Users/hy/.ssh/jwt_rsa.pub"

[auth.google]
encrypted = true
client_id = "kPmVQs1VcRWa7lm9afOcZzd2wxfLE4Ws441Y5H+MeAs735CVMgSLbUDsqR5vMJSkVLeWP1ScpLmS1hiEvfkTNcOYic3iMojstNDNSQLrUaU="
client_secret = "vWl5RU38iFcid5JI/j610qcp0aoHOEvWI6+Q/QrKRbY="
call_back_url = "http://localhost:9999/oauth2/google/callback"

[auth.facebook]
encrypted = true
client_id = "VZSYxmfcqQFZNUP7Tzchtg=="                         #app_id
client_secret = "aVd1AHW1PVsChVWcI0uhim0etWgg+9Mj2x+puSBTHHM=" #app secret
call_back_url = "http://localhost:9999/oauth2/facebook/callback"

[mysql]
encrypted = false
host = "localhost"
port = 3306
dbname = "maindb"
user = "testuser"
pass = "12345678"

[mysql.test]
encrypted = false
host = "localhost"
port = 3306
dbname = "testdb"
user = "testuser"
pass = "12345678"

[redis]
encrypted = false
host = "localhost"
port = 6379
pass = ""
session = false

[mongodb]
encrypted = false
host = "localhost"
port = 27017
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

[aws]
encrypted = false
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

[develop]
profile_enable = false
recover_enable = true