#local, heroku, docker, staging, production
environment = "local"

[server]
host = "localhost"
port = 9999
referer = "http://localhost"

[server.docs]
path = "/Users/hy/work/go/src/github.com/hiromaily/go-gin-wrapper"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[proxy]
enable = false
host = "127.0.0.1"

[api]
header = "X-Custom-Header-Gin"
key = "key12345"
only_ajax = true

[mysql]
host = "localhost"
port = 3306
dbname = "maindb"
user = "testuser"
pass = "12345678"

[mysql.test]
host = "localhost"
port = 3306
dbname = "testdb"
user = "testuser"
pass = "12345678"


[redis]
host = "localhost"
port = 6379
pass = ""
session = false

[aws]
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

[profile]
enable = false
