#local, heroku, docker, staging, production
environment = "local"

[server]
scheme = "http"
host = "localhost"
port = 9999

[server.docs]
path = "/Users/hy/work/go/src/github.com/hiromaily/go-gin-wrapper"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "localhost"
port = 9990
web_port = [ 8080, 8081, 8082 ]

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

[api]
only_ajax = true

[api.cors]
enabled = true
origins = ["http://127.0.0.1:8000"]
#headers = ["Origin", "X-Requested-With", "Content-Type", "Accept", "Authorization"]
headers = ["X-Custom-Header-CORS", "X-Custom-Header-Gin"]
methods = ["GET", "OPTIONS"]
credentials = false

[api.header]
enabled = true
header = "X-Custom-Header-Gin"
key = "key12345"

[api.jwt]
mode = 0   #0:off, 1:HMAC, 2:RSA  # it's for check
secret_code = ""
private_key = "/Users/hy/.ssh/jwt_rsa"
public_key = "/Users/hy/.ssh/jwt_rsa.pub"

[auth]

[auth.google]
#encrypted = false
#client_id = "275878174798-fn57e2017fp30ikecfho446gjntfiff2.apps.googleusercontent.com"
#client_secret = "R_gybCfMUxg2GJ63ZKwRsTEV"
#call_back_url = "http://localhost:8080/oauth2/google/callback"
encrypted = true
client_id = "kPmVQs1VcRWa7lm9afOcZzd2wxfLE4Ws441Y5H+MeAs735CVMgSLbUDsqR5vMJSkVLeWP1ScpLmS1hiEvfkTNcOYic3iMojstNDNSQLrUaU="
client_secret = "vWl5RU38iFcid5JI/j610qcp0aoHOEvWI6+Q/QrKRbY="
call_back_url = "http://localhost:8080/oauth2/google/callback"

[auth.facebook]
#encrypted = false
#client_id = "626742984171908"                      #app_id
#client_secret = "1bfb47b6680c8348c583e3f51ca7811a" #app secret
#call_back_url = "http://localhost:8080/oauth2/facebook/callback"
encrypted = true
client_id = "VZSYxmfcqQFZNUP7Tzchtg=="                         #app_id
client_secret = "aVd1AHW1PVsChVWcI0uhim0etWgg+9Mj2x+puSBTHHM=" #app secret
call_back_url = "http://localhost:8080/oauth2/facebook/callback"

[mysql]
encrypted = false
host = "localhost"
port = 13306
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

[mysql.test]
encrypted = false
host = "localhost"
port = 13306
dbname = "hiromaily2"
user = "root"
pass = "root"

[redis]
encrypted = false
host = "localhost"
port = 16379
pass = "password"
session = true

[mongodb]
encrypted = false
host = "localhost"
port = 27017
dbname = "hiromaily"
user = "hiromaily"
pass = "12345678"

[aws]
encrypted = false
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

[develop]
profile_enable = false
recover_enable = false
