#local, heroku, docker, staging, production
environment = "travis"

[server]
scheme = "http"
host = "hiromaily.com"
port = 9999
num = 1

[server.docs]
path = "/home/travis/gopath/src/github.com/hiromaily/go-gin-wrapper"

[server.log]
level = 1
path = "/var/log/goweb/ginserver.log"

[server.session]
name = "go-web-ginserver"
key = "secretskey123456"
max_age =  300     #(s)
secure = false    #set false in development environment, production environment requires true
http_only = true

[server.basic_auth]
user = "web"
pass = "test"

[proxy]
mode = 0   #0:off, 1:go, 2:nginx

[proxy.server]
scheme = "http"
host = "127.0.0.1"
port = 9990

[proxy.server.log]
level = 1
path = "/var/log/goweb/proxy.log"

[auth]

[auth.api]
header = "X-Custom-Header-Gin"
key = "key12345"
only_ajax = true

[auth.jwt]
mode = 0   #0:off, 1:HMAC, 2:RSA
secret_code = "secret1234567890"
private_key = ""
public_key = ""

[auth.google]
encrypted = true
client_id = "kPmVQs1VcRWa7lm9afOcZzd2wxfLE4Ws441Y5H+MeAs735CVMgSLbUDsqR5vMJSkVLeWP1ScpLmS1hiEvfkTNcOYic3iMojstNDNSQLrUaU="
client_secret = "vWl5RU38iFcid5JI/j610qcp0aoHOEvWI6+Q/QrKRbY="
call_back_url = "http://localhost:9999/oauth2/google/callback"

[auth.facebook]
encrypted = true
client_id = "VZSYxmfcqQFZNUP7Tzchtg=="                         #app_id
client_secret = "aVd1AHW1PVsChVWcI0uhim0etWgg+9Mj2x+puSBTHHM=" #app secret
call_back_url = "http://localhost:9999/oauth2/facebook/callback"

[mysql]
encrypted = true
host = "us-cdbr-iron-east-04.cleardb.net"
port = 3306
dbname = "heroku_53533e2ad9f9475"
user = "bc19f40b56274b"
pass = "cfee2ebd"

[mysql.test]
encrypted = true
host = "us-cdbr-iron-east-04.cleardb.net"
port = 3306
dbname = "heroku_53533e2ad9f9475"
user = "bc19f40b56274b"
pass = "cfee2ebd"

[redis]
encrypted = true
host = "ec2-54-197-242-4.compute-1.amazonaws.com"
port = 9769
pass = "p7nkpdqindrp4o145oveqpet6ut"
session = true

[mongodb]
encrypted = true
host = "ds161495.mlab.com"
port = 61495
dbname = "heroku_7lbnd77m"
user = "heroku_7lbnd77m"
pass = "7r8f631nv2idt0fhj9ok9714j9"

[aws]
encrypted = true
access_key = "XXXXXXXXXXXX"
secret_key = "XXXXXXXXXXXX"
region = "ap-northeast-1"

[develop]
profile_enable = false
recover_enable = true